version: '3'

services:
  client:
    container_name: video-feed-app
    image: client-nginx-angularjs
    environment:
      NODE_ENV: production
    build:
      context: .
      dockerfile: prod.dockerfile
      args:
        NODE_ENV: production
    ports:
      - "8080:80"